### ISSUE TITLE
Double quotes in the source path are stripped from opusenc argument

### ISSUE THREAD

**Issue by gyratory** [smxi/acxi#1]
Hi,

acxi is a wonderful tool, thank you so much for creating it! I am encountering a problem when transcoding my library, here is the debug output:

```
-----------------------------------------------------------------
ENCODE: /home/user/Music/Library/TRakker/GWAVE Clubsound Project "Somersault" [Limited Edition]/04 - Heaven's Fall (zts Remix).flac ==> 
        /home/user/Music/transcode/TRakker/GWAVE Clubsound Project "Somersault" [Limited Edition]/04 - Heaven's Fall (zts Remix).opus
/home/user/Music/Library/TRakker/GWAVE Clubsound Project Somersault [Limited Edition]/04 - Heaven's Fall (zts Remix).flac: No such file or directory
To opus result: 256
-----------------------------------------------------------------
ENCODE: /home/user/Music/Library/marble/未来スコープ/08 smile ~the landscape through a "MIRAISCOPE"~.flac ==> 
        /home/user/Music/transcode/marble/未来スコープ/08 smile ~the landscape through a "MIRAISCOPE"~.opus
/home/user/Music/Library/marble/未来スコープ/08 smile ~the landscape through a MIRAISCOPE~.flac: No such file or directory
To opus result: 256
===========================================================================
```
As seen above, opusenc fails to transcode anything with double quotes in the path, whether it's the directory or filename. (The destination directory for "Somersault" album does not contain any opus files, and the 未来スコープ album is only missing track number 8).

**Comment by gyratory** [comment]
Not sure what happened to my original comment. I am posting it again:

Thanks for acxi, it is a wonderful tool!

I am encountering a problem where acxi does not pass quotes in the source path:
```
-----------------------------------------------------------------
ENCODE: /home/user/Music/Library/TRakker/GWAVE Clubsound Project "Somersault" [Limited Edition]/04 - Heaven's Fall (zts Remix).flac ==> 
        /home/user/Music/transcode/TRakker/GWAVE Clubsound Project "Somersault" [Limited Edition]/04 - Heaven's Fall (zts Remix).opus
/home/user/Music/Library/TRakker/GWAVE Clubsound Project Somersault [Limited Edition]/04 - Heaven's Fall (zts Remix).flac: No such file or directory
To opus result: 256
-----------------------------------------------------------------
ENCODE: /home/user/Music/Library/marble/未来スコープ/08 smile ~the landscape through a "MIRAISCOPE"~.flac ==> 
        /home/user/Music/transcode/marble/未来スコープ/08 smile ~the landscape through a "MIRAISCOPE"~.opus
/home/user/Music/Library/marble/未来スコープ/08 smile ~the landscape through a MIRAISCOPE~.flac: No such file or directory
To opus result: 256
===========================================================================
All done updating. Enjoy your music!

```

I checked the destination directory and here's the results:
* The "Somersault" album has no opus files
* The "未来スコープ" album is only missing track 8

**Comment by smxi** [comment]
This was just a matter of escaping " in the source and destination paths when using oggenc/opusenc, and lame. Try the fixed version from: wget -O acxi smxi.org/opt/acxi
Once you confirm the fix, I'll update the main version in github.

**Comment by gyratory** [comment]
Currently I am running the script on Kubuntu 18.04 with perl v5.26.1 and libopus v1.3.  
Some observations with the updated script:  
1. Double quotes and Japanese Kanji/Kana are no problem now :thumbsup:
2. Really weird but valid linux filenames like `/home/user/Music/Library/Hiroyuki Sawano/青の祓魔師 Plugless/1-02 Me & Creed <Lite-Tone-Happy部 3:な>.flac` cause problems. I believe this is due to the colon (might be a Japanese character instead of a regular one) towards the end. There may also be problems with '$' as well.

```
PROCESSING DATA TYPE: flac
-----------------------------------------------------------------
ENCODE: /home/user/Music/Library/Hiroyuki Sawano/Re:CREATORS Original Soundtrack/1-03 Re:3$penS.flac ==> 
        /home/user/Music/transcode/Hiroyuki Sawano/Re:CREATORS Original Soundtrack/1-03 Re:3$penS.opus
/home/user/Music/Library/Hiroyuki Sawano/Re:CREATORS Original Soundtrack/1-03 Re:3.flac: No such file or directory
To opus result: 256
-----------------------------------------------------------------
ENCODE: /home/user/Music/Library/Hiroyuki Sawano/青の祓魔師 オリジナル・サウンドトラック 2/13 Hiroyuki Sawano - 交響$weet 1st-Mov.:st-RING.flac ==> 
        /home/user/Music/transcode/Hiroyuki Sawano/青の祓魔師 オリジナル・サウンドトラック 2/13 Hiroyuki Sawano - 交響$weet 1st-Mov.:st-RING.opus
/home/user/Music/Library/Hiroyuki Sawano/青の祓魔師 オリジナル・サウンドトラック 2/13 Hiroyuki Sawano - 交響 1st-Mov.:st-RING.flac: No such file or directory
To opus result: 256
-----------------------------------------------------------------
ENCODE: /home/user/Music/Library/Hiroyuki Sawano/青の祓魔師 オリジナル・サウンドトラック 2/14 Hiroyuki Sawano - 交響$weet 2nd-Mov.:STN-blood.flac ==> 
        /home/user/Music/transcode/Hiroyuki Sawano/青の祓魔師 オリジナル・サウンドトラック 2/14 Hiroyuki Sawano - 交響$weet 2nd-Mov.:STN-blood.opus
/home/user/Music/Library/Hiroyuki Sawano/青の祓魔師 オリジナル・サウンドトラック 2/14 Hiroyuki Sawano - 交響 2nd-Mov.:STN-blood.flac: No such file or directory
To opus result: 256
-----------------------------------------------------------------
ENCODE: /home/user/Music/Library/Hiroyuki Sawano/青の祓魔師 オリジナル・サウンドトラック 2/15 Hiroyuki Sawano - 交響$weet 3rd-Mov.:call ME.flac ==> 
        /home/user/Music/transcode/Hiroyuki Sawano/青の祓魔師 オリジナル・サウンドトラック 2/15 Hiroyuki Sawano - 交響$weet 3rd-Mov.:call ME.opus
/home/user/Music/Library/Hiroyuki Sawano/青の祓魔師 オリジナル・サウンドトラック 2/15 Hiroyuki Sawano - 交響 3rd-Mov.:call ME.flac: No such file or directory
To opus result: 256
-----------------------------------------------------------------
ENCODE: /home/user/Music/Library/Hiroyuki Sawano/青の祓魔師 オリジナル・サウンドトラック 2/16 Hiroyuki Sawano - 交響$weet 4th-Mov.:f.flac ==> 
        /home/user/Music/transcode/Hiroyuki Sawano/青の祓魔師 オリジナル・サウンドトラック 2/16 Hiroyuki Sawano - 交響$weet 4th-Mov.:f.opus
/home/user/Music/Library/Hiroyuki Sawano/青の祓魔師 オリジナル・サウンドトラック 2/16 Hiroyuki Sawano - 交響 4th-Mov.:f.flac: No such file or directory
To opus result: 256
===========================================================================
All done updating. Enjoy your music!
```

**Comment by smxi** [comment]
It's the $, not the :.

Verified with $ in file name. Try the new fixed smxi.org/opt/acxi and that part should work.

This is actually a shell expansion happening, which makes sense.

Your music set is very good for exposing some of these shortcomings and these fixes should be good to help everyone.

Update acxi from smxi.org and let me know if it now works.

You could actually see this in the debugger output because flac said a file name did not exist, that's because the part after the $ that was not a space was treated like a variable name, empty in this case.

**Comment by smxi** [comment]
Oh, also, note that fat32/vfat will not like some of the characters, but that's not really an acxi issue, > for example it doesn't like. 

There's an ogg/opus encode option to change one character for another, but inside of acxi, to preserve other functionality, I'd have to do that in the file / directory list tool, since it has to translate it back and forth from original to copy so it can recognize the file/ directory names in the compressed section.

But your specific example should now work with latest acxi.

**Comment by smxi** [comment]
Thank you for taking the time to post a bug report, and to follow up with it. If you are sure you can't find any other errors, I will close this issue and mark it solved, but I'll wait until tomorrow to make sure.

Then 3.1.1 will become the latest acxi here, so thanks.

**Comment by smxi** [comment]
acxi 3.1.1 is now committed, thanks for the bug / issue report.
