### ISSUE TITLE
[Debian 10] acxi acts as though I have provided no paths

### ISSUE THREAD

**Issue by Strife89** [smxi/acxi#2]
I get the following output while attempting to test acxi for a large conversion:
```
michael@saanaito:~$ acxi --test -i /media/nas/Robert\'s\ Ripped\ Music/main -o /media/nas/Robert\'s\ Ripped\ Music/mp3
\===========================================================================
Running acxi pretests.
Checking log/screen output level..................... Supported: 3
---------------------------------------------------------------------------
Checking source / destination directories............ 
Error 1: The paths for the following directories are missing:
  Source Directory: /path/to/source/directory
  Destination Directory: /path/to/your/output/directory
Unable to continue. Please check the directory paths you provided.
```

/media/nas is a SMB share, in case that matters. It is auto-mounted through fstab:
`//kabigon.local/home /media/nas cifs username=michael,password=[my password],uid=nobody,iocharset=utf8,noperm 0 0`

**Comment by smxi** [comment]
If in doubt, use "" on shell command lines.

acxi --test -i "/media/nas/Robert's Ripped Music/main" -o "/media/nas/Robert's Ripped Music/mp3"

that's probably your problem, you tried to outguess the way paths are handled, don't do that, just double quote the paths. I've converted tons of directories with spaces and ' in the paths, no issues.

**Comment by smxi** [comment]
Oh, sorry, lol, look at what you posted, -i is input type, -o is output type. You're looking for --source/-s --destination/-d

**Comment by smxi** [comment]
Please note, in order to make such user errors more obvious, acxi 3.1.2 now will run all the pretests, and only exit at the end of them if one of the tests failed.

**Comment by smxi** [comment]
Please note that the README had some glitches in it, that could lead one to use the wrong options, that's been corrected and clarified as well.

**Comment by Strife89** [comment]
Thanks for the quick reply and updates! I think I'm still overlooking something; with fixed arguments and an addition, I get this:

```
acxi -o mp3 -s /media/nas/Robert\'s\ Ripped\ Music/main -d /media/nas/Robert\'s\ Ripped\ Music/mp3
Running acxi pretests.
Checking log/screen output level..................... Supported: 1
Checking source / destination directories............ Directories: exist
Checking input and output types...................... Valid: flac(in) mp3(out)
Checking quality support for mp3..................... Supported: 3 (mp3)
Checking audio conversion tool path.................. Available: 
 /usr/bin/lame /usr/bin/flac /usr/bin/metaflac 
Starting sync of /media/nas/Robert's Ripped Music/main
 to /media/nas/Robert's Ripped Music/mp3
Updating destination directories..................... 
Creating new directory: /media/nas/Robert's Ripped Music/mp3/2Pac
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Alice In Chains
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Black Sabbath
Creating new directory: /media/nas/Robert's Ripped Music/mp3/BlindMelon
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Dave Matthews
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Eminem
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Randy Howell
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Various
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Various Artists
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Carlos Montoya
Creating new directory: /media/nas/Robert's Ripped Music/mp3/James Brown
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Kiss
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Nirvana
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Pink Floyd
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Randy Edelman
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Right Said Fred
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Robert Randolph & The Family Band
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Santana
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Seven Nations
Creating new directory: /media/nas/Robert's Ripped Music/mp3/ZZ Top
Creating new directory: /media/nas/Robert's Ripped Music/mp3/classical
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Unknown Artist
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Thomas Newman
Creating new directory: /media/nas/Robert's Ripped Music/mp3/Van Halen
Creating new directory: /media/nas/Robert's Ripped Music/mp3/The Beatles
Creating new directory: /media/nas/Robert's Ripped Music/mp3/The Doors
Processing bmp data type............................. None found
Processing doc data type............................. None found
Processing docx data type............................ None found
Processing gif data type............................. None found
Processing jpg data type............................. None found
Processing jpeg data type............................ None found
Processing odt data type............................. None found
Processing pdf data type............................. None found
Processing png data type............................. None found
Processing tif data type............................. None found
Processing txt data type............................. None found
Processing flac data type............................ None found
Updating completed. Enjoy your music!
michael@saanaito:~$ 
```

**Comment by smxi** [comment]
I tested acxi with nfs4 mounted remote file system, more or less like what you're trying, and it worked fine. I further tested with the spaces escaped like you're doing, and that worked fine. Note as a rule, I'd suggest dropping that habit and using "/path/with spaces" but it doesn't seem to trigger any issues in this case.

Haven't tested smb shares, and nfs isn't exactly the same logic, so that's the only variable left, well except for more spaces in the path names. However the Santana directory should have had data in it since that doesn't have a space in the album name.

My conclusion is that something else is up.

Also, you haven't updated to the new acxi, though that shouldn't have any technical conversion differences, but it's testing and output is better.

As you can see from your test, it created the sub directories fine, but failed to get any file data.

**Comment by smxi** [comment]
While I haven't used samba in a while, I checked a smb.conf file, and noted there is a:

browseable=no

type option for the share, also, there are permissions on the share.

From your output, it looks like the shared directories are not being assigned the proper permissions, or the mount you're using isn't triggering them. 

I'd say this is an smb problem, not an acxi problem, and you can fairly easily check that by mounting the share, then seeing on the command line what you can and can't do.

So, as suggested, ls -l in the Santana directory.

If you get no results, the directory is not browseable, that's my first guess since acxi got not file information to copy/convert.

There may also be read permissions limits, and a variety of other things, none of which should be connected to acxi.

But I can confirm that a raw nfs4 conversion test with spaces in path works fine, so there's nothing intrinsic in networked remote connections that will make it fail, but smb has much more granular permissions than nfs, so it's probably an smb configuration or mount arguments problem.

**Comment by Strife89** [comment]
```
michael@saanaito:~/dev/acxi$ ls -l /media/nas/Robert\'s\ Ripped\ Music/main/Santana/
total 0
drwxr-xr-x 2 nobody root 0 Jul  3 11:11 Supernatural
michael@saanaito:~/dev/acxi$ ls -l /media/nas/Robert\'s\ Ripped\ Music/main/Santana/Supernatural/
total 509836
-rwxr-xr-x 1 nobody root 43134196 Jul  3 11:04 '01 - (Da Le) Yaleo.flac'
-rwxr-xr-x 1 nobody root 41970528 Jul  3 11:04 '02 - Love of My Life (feat. Dave Mathews).flac'
-rwxr-xr-x 1 nobody root 34766454 Jul  3 11:05 '03 - Put Your Lights On (feat. Everlast).flac'
-rwxr-xr-x 1 nobody root 35527048 Jul  3 11:05 '04 - Africa Bamba.flac'
-rwxr-xr-x 1 nobody root 37401534 Jul  3 11:06 '05 - Smooth (feat. Rob Thomas).flac'
-rwxr-xr-x 1 nobody root 41561211 Jul  3 11:06 '06 - Do You Like the Way (feat. Lauren Hill & Cee-Lo).flac'
-rwxr-xr-x 1 nobody root 25441087 Jul  3 11:07 '07 - Maria Maria.flac'
-rwxr-xr-x 1 nobody root 39656791 Jul  3 11:07 '08 - Migra.flac'
-rwxr-xr-x 1 nobody root 33444656 Jul  3 11:08 '09 - Corazon Espinado (feat. Maná).flac'
-rwxr-xr-x 1 nobody root 35206010 Jul  3 11:08 '10 - Wishing It Was (feat. Eagle-Eye Cherry).flac'
-rwxr-xr-x 1 nobody root 28856152 Jul  3 11:09 '11 - El Farol.flac'
-rwxr-xr-x 1 nobody root 43692697 Jul  3 11:09 '12 - Primavera.flac'
-rwxr-xr-x 1 nobody root 81385334 Jul  3 11:10 '13 - The Calling (feat. Eric Clapton).flac'
-rwxr-xr-x 1 nobody root     1056 Jul  3 11:11 'Santana - Supernatural.flac.m3u'
michael@saanaito:~/dev/acxi$ 
```
For context: I'm ripping directly to my NAS because my desktop's local storage is pretty full already. (I'm coming up on 30 GB of FLACs!)
Since the networked storage factor is beyond the scope of your project, I'll just copy the FLACs to a flash drive and attempt to run acxi on those.

**Comment by smxi** [comment]
This may or may not be a function of the Perl file browser tool being used internally in acxi, File::Find. I don't exactly how that one works, it's kind of a black box, but since you can browse the contents on the command line, I have to assume there's some subtle difference in permissions going on here, but I don't know what exactly that would be. 

The 'nobody root' ownership might be involved, but I'm not up on samba mount logic, but it might be that your permissions aren't setup quite correctly on the nas system. I used to do smb stuff for clients but I haven't dealt with it for many years, but I do remember that even slightly wrong permissions would result in strange errors, like being unable to delete folders in windows, etc. A small permission tweak would resolve the issue.

I don't know if Perl's File::Find is running as the same user that is running acxi, I assume it is, but I'm not positive. It looks as if everyone, and the group, have read/execute permissions on the remote smb system, which should mean the directory structure is not browseable, but apparently it isn't for Perl's module File for some reason.

I'd have to probably set up a samba thing again, then see if I can emulate the failure to really debug it, if it can be debugged. This might also be one for PerlMonks to answer since it's getting pretty obscure.

It might be worth figuring out it out because smb is the most normal networked file system in most configurations out there, so it's either going to be a configuration setting in samba, or it's a glitch with File::Find, or the latter needs something else to happen for it to browse a mounted samba network share.

**Comment by smxi** [comment]
Notes to myself, I don't know the status of these issues, and testing it requires debugging code run on end user systems:
File::Find won't iterate through CIFS share withouth "dont_use_nlink"
https://www.perlmonks.org/?node_id=1180606

https://metacpan.org/pod/File::Find

From PerlMonks: https://www.perlmonks.org/?node_id=32791

```
use strict;
use File::Find;
my $dir = shift;
my ($with, $without);

print "Counting files in $dir\n";

# This is the default on Linux
$File::Find::dont_use_nlink = 0;
find(sub { $without++ }, $dir);

$File::Find::dont_use_nlink = 1;
find(sub { $with++ }, $dir);

print "With \$File::Find::dont_use_nlink = 0: $without files found\n";
print "With \$File::Find::dont_use_nlink = 1: $with files found\n";
```

**Comment by smxi** [comment]
For my own satisfaction, can you try these two tests:

At the top of the acxi file, paste in the following under 
(about line 58)
`use File::Find`

`$File::Find::dont_use_nlink = 0;`

then try acxi again with the smb mounts.

if same result, change the 0 to 1, like so:

`$File::Find::dont_use_nlink = 1;`

Are the results different? are they the same? does one result in the action happening as hoped for? Use the --test flag to avoid unwanted actions.

**Comment by smxi** [comment]
If you can run these tests, I can add an option to trigger this in case an smb cifs mounted file system returns no files listed from File::Find, but I can't safely just add that since it can have negative results depending on the OS / platform being used if I understand it right.

**Comment by Strife89** [comment]
Looks like `dont_use_nlink = 1` does the trick! Thanks!

**Comment by smxi** [comment]
Oh! great. Once we'd ruled out other issues, it got easier to find what it was. luckily finding File::Find with cifs failures is easy once you know what to look for.

I've read a bit more, and it appears that dont_use_nlink is supposed to be 1, but for some reason it's not in this scenario, so I've set it to default to 1 internally, with an override flag --nlink and configuration option DONT_USE_NLINK which can be set to 0 or 1. 

Can you try the new acxi, which is version 3.1.3 and see if this works as expected, that is, this should just work on your system without any changes after you have tested it. Delete one or two of the mp3 directories you've generated and then confirm that acxi 3.1.3 finds and updates the collection.

This may be all that is required.

**Comment by Strife89** [comment]
My NAS's `smb.conf`, just in case it proves helpful for testing:
```
[michael@kabigon ~]$ cat /etc/config/smb.conf
[global]
passdb backend = smbpasswd
workgroup = WORKGROUP
	security=user
	server string=NAS Server
	encrypt passwords = Yes
username level = 0
map to guest = Bad User
null passwords = yes
	max log size = 10
name resolve order = host bcast
socket options = TCP_NODELAY SO_KEEPALIVE SO_SNDBUF=65536 SO_RCVBUF=65536
os level = 20
preferred master = no
	dns proxy = No
	smb passwd file=/etc/config/smbpasswd	
	username map = /etc/config/smbusers
guest account = guest
	directory mask = 0777
	create mask = 0777
oplocks = yes
	locking = yes
disable spoolss = no
load printers = yes
veto files = /.AppleDB/.AppleDouble/.AppleDesktop/:2eDS_Store/Network Trash Folder/Temporary Items/TheVolumeSettingsFolder/.@__thumb/.@__desc/:2e*/.@__qini/.Qsync/.@upload_cache/.qsync/.qsync_sn/.@qsys/.streams/.digest/
	delete veto files = yes
map archive = no
map system = no
map hidden = no
map read only = no
deadtime = 10
server role = auto
use sendfile = yes
unix extensions = no
store dos attributes = yes
client ntlmv2 auth = yes
dos filetime resolution = no
wide links = yes
force unknown acl user = yes
template homedir = /share/homes/DOMAIN=%D/%U
inherit acls = no
domain logons = no
case sensitive = auto
domain master = auto
local master = no
enhance acl v1 = yes
remove everyone = no
conn log = no
kernel oplocks = no
max protocol = SMB2_10
smb2 leases = yes
durable handles = yes
kernel share modes = no
posix locking = no
lock directory = /share/MD0_DATA/.samba/lock
state directory = /share/MD0_DATA/.samba/state
cache directory = /share/MD0_DATA/.samba/cache
printcap cache time = 0
acl allow execute always = yes
server signing = disabled
streams_depot:delete_lost = yes
streams_depot:check_valid = no
fruit:nfs_aces = no
fruit:veto_appledouble = no
winbind enum groups = Yes
winbind enum users = Yes
winbind expand groups = 1
pid directory = /var/lock
printcap name = cups
printing = cups
show add printer wizard = no
vfs objects =  catia fruit qnap_macea streams_depot
[Multimedia]
comment = System default share
path = /share/MD0_DATA/Multimedia
browsable = yes
oplocks = yes
ftp write only = no
recycle bin = yes
recycle bin administrators only = no
qbox = no
public = yes
invalid users = "guest"
read list = @"everyone"
write list = "admin","michael",@"michael"
valid users = "root",@"everyone","admin","michael",@"michael"
inherit permissions = yes
smb encrypt = disabled
mangled names = yes
[Download]
comment = System default share
path = /share/MD0_DATA/Download
browsable = yes
oplocks = yes
ftp write only = no
recycle bin = yes
recycle bin administrators only = no
qbox = no
public = yes
invalid users = "guest"
read list = 
write list = "admin","michael",@"michael"
valid users = "root","admin","michael",@"michael"
inherit permissions = yes
smb encrypt = disabled
mangled names = yes
[Web]
comment = System default share
path = /share/MD0_DATA/Web
browsable = yes
oplocks = yes
ftp write only = no
recycle bin = yes
recycle bin administrators only = no
qbox = no
public = yes
invalid users = "guest"
read list = @"michael"
write list = "admin","michael"
valid users = "root","admin","michael",@"michael"
inherit permissions = yes
smb encrypt = disabled
mangled names = yes
[Public]
comment = System default share
path = /share/MD0_DATA/Public
browsable = yes
oplocks = yes
ftp write only = no
recycle bin = yes
recycle bin administrators only = no
qbox = no
public = yes
invalid users = "guest"
read list = @"everyone"
write list = "admin","michael",@"michael"
valid users = "root",@"everyone","admin","michael",@"michael"
inherit permissions = yes
smb encrypt = disabled
mangled names = yes
[homes]
comment = System default share
path = /share/MD0_DATA/homes
browsable = yes
oplocks = yes
ftp write only = no
recycle bin = yes
recycle bin administrators only = no
qbox = no
public = yes
invalid users = 
read list = 
write list = "admin","michael",@"michael"
valid users = "root","admin","michael",@"michael"
inherit permissions = yes
smb encrypt = disabled
mangled names = yes
[printers]
use client driver = yes
writable = no
browsable = no
printable = yes
guest ok = yes
path = /var/spool/smb
[home]
comment = Home
path = %H
browsable = yes
oplocks = yes
ftp write only = no
inherit permissions = yes
invalid users = guest
writable = yes
read list = "%u"
write list = "%u"
valid users = "%u"
root preexec = /sbin/create_home -u '%q'
[USBDisk1]
comment = USB storage share
path = /share/external/sdt1
browsable = yes
oplocks = no
ftp write only = no
recycle bin = no
recycle bin administrators only = no
qbox = yes
public = yes
invalid users = "guest"
read list = 
write list = "admin","michael"
valid users = "root","admin","michael"
inherit permissions = yes
smb encrypt = disabled
mangled names = no
nt acl support = no
q use receivefile = no
vfs objects =  
[michael@kabigon ~]$ 
```

**Comment by smxi** [comment]
That's useful for others who might have issues, thanks. 

In this case, it appears to be focused on File::Find itself, which surprised me, but it was the most obvious suspect after excluding other causes.

Can you confirm that acxi 3.1.13 works as expected now without any modifications?

My only uncertainty is where I am setting this setting, I'm not fully clear on the scope of that, but I think it's fine, but not positive.

**Comment by Strife89** [comment]
Just did a `git pull` to get on the current version, and did a new run as you've asked. It's working!

**Comment by smxi** [comment]
Excellent! Thanks for doing the tests, this issue would probably impact many people who use NAS with cifs mounts, not just you, so this was a good thing to get resolved. I should probably set up a test scenario myself with cifs mount as well to make sure, but it looks like it's all fine. Looks like this will be the new acxi then, that's good.

Thanks for finding not just one, but two failure issues, one being bad documentation on the README page, and weak error handling on the validation tests, but also an actual real issue with a situation that could impact other users, and probably has at some point.
