### ISSUE TITLE
Sync audio in hidden directories

### ISSUE THREAD

**Issue by curegit** [smxi/acxi#8]
Hi.
I'm interested in acxi because of its convenience. 
 
However, it seems that acxi doesn't sync audio files in hidden directories (its names start with dots). 
For example, `music/flac/Phil Collins/...Hits/01. Another Day in Paradise.flac` won't be encoded or transferred to the destination because it's in `...Hits` directory, treated as a hidden directory. 

Can I sync audio in hidden directories with acxi?
Otherwise, can I request it as a new feature or option?

Thanks.

**Comment by smxi** [comment]
The answer to your questions are:

1. No, you can't sync audio in hidden files, since the entire purpose of filtering out hidden files is to not sync hidden files, lol.

2. yes, you can request an override switch to remove that behavior, since that's trivial to do.

**Comment by smxi** [comment]
Main acxi branch now has this feature, probably time to do a new official 'release' too, but I'll wait until it's confirmed working as expected. Note that there are many good reasons to exclude dot files by default, so if something goes wrong, that's not my problem.

**Comment by smxi** [comment]
switched --hidden to --dot to make it more intuitive, since you want to include dot files.

**Comment by curegit** [comment]
I really appreciate your quick commitment.
I confirmed that it worked as I expected, so I am glad to use this application.
Thank you very much.
